openapi: 3.0.0
info:
  title: User Registration API
  version: 1.0.0

paths:
  /users:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    User:
      type: object
      required:
        - name
        - email
        - password
        - phones
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        phones:
          type: array
          items:
            $ref: '#/components/schemas/Phone'

    Phone:
      type: object
      required:
        - number
        - citycode
        - contrycode
      properties:
        number:
          type: string
        citycode:
          type: string
        contrycode:
          type: string

    UserResponse:
      type: object
      properties:
        id:
          type: string
        created:
          type: string
          format: date-time
        modified:
          type: string
          format: date-time
        last_login:
          type: string
          format: date-time
        token:
          type: string
        isactive:
          type: boolean

    ErrorResponse:
      type: object
      properties:
        mensaje:
          type: string
