#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true
#key:
#  validation:
#    regex: "^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$"
